### ISSUE TITLE
About UAVDT Dataset

### ISSUE THREAD

**Issue by Zhuyuan-yuan** [pingyang1117/PRBNet_PyTorch#3]
How do you handle the ignored area of the dataset UAVDT? Do you have the relevant processing code?
Thank for your help?

**Comment by pingyang1117** [comment]
Dear @Zhuyuan-yuan, please train the images with the "_filename__gt_whole.txt," not the ignored one. We don't want our model to consider the small object or some critical cases as background. You could disable the ignored area for the evaluation process to get the results.
