### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by tzhou8** [pingyang1117/PRBNet_PyTorch#5]
Hi dear author, when I reproduced this mode, I encountered this error like this, I just want to know how can I fix this issue, thanks, looking forward to your reply.
![image](https://user-images.githubusercontent.com/34847922/227544090-59780302-dcd9-4019-b08b-594492a61d9c.png)

**Comment by pingyang1117** [comment]
Please confirm whether you have successfully downloaded the complete prb-fpn.pt file. Additionally, would you mind sharing your command line with me?

**Comment by tzhou8** [comment]
Thanks, issues was resolved.
