### ISSUE TITLE
NameError: name 'BottleneckMSP' is not defined

### ISSUE THREAD

**Issue by can-git** [pingyang1117/PRBNet_PyTorch#6]
Hello,
I've got a NameError when try to train my custom dataset with "PRB-FPN-ELAN.yaml". Here's the issue:

`Traceback (most recent call last):
  File "train.py", line 616, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 88, in train
    model = Model(opt.cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/home/can/Desktop/MOT/BoT-SORT/PRBNet_PyTorch/prb/models/yolo.py", line 529, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch])  # model, savelist
  File "/home/can/Desktop/MOT/BoT-SORT/PRBNet_PyTorch/prb/models/yolo.py", line 756, in parse_model
    BottleneckMSP,BottleneckMSPA,BottleneckMSPB,
NameError: name 'BottleneckMSP' is not defined
`

When I searched the yolo.py at line 756:

`n = max(round(n * gd), 1) if n > 1 else n  # depth gain
        if m in [nn.Conv2d, Conv, RobustConv, RobustConv2, DWConv, GhostConv, RepConv, RepConv_OREPA, DownC, 
                 SPP, SPPF, SPPCSPC, GhostSPPCSPC, MixConv2d, Focus, Stem, GhostStem, CrossConv, CBAM,
                 Bottleneck, BottleneckCSPA, BottleneckCSPB, BottleneckCSPC, 
                 BottleneckMSP,BottleneckMSPA,BottleneckMSPB,
                 RepBottleneck, RepBottleneckCSPA, RepBottleneckCSPB, RepBottleneckCSPC,  
                 Res, ResCSPA, ResCSPB, ResCSPC, 
                 RepRes, RepResCSPA, RepResCSPB, RepResCSPC, 
                 ResX, ResXCSPA, ResXCSPB, ResXCSPC, 
                 RepResX, RepResXCSPA, RepResXCSPB, RepResXCSPC, 
                 Ghost, GhostCSPA, GhostCSPB, GhostCSPC,
                 SwinTransformerBlock, STCSPA, STCSPB, STCSPC,
                 SwinTransformer2Block, ST2CSPA, ST2CSPB, ST2CSPC]:`

In this code block, I deleted line 756, which was "BottleneckMSP,BottleneckMSPA,BottleneckMSPB," and now my training has started successfully.

I just want to know what was the reason because I am new. Is it because I also have "PRB-FPN-MSP.yaml" in the cfg folder ? Or not will I face with any issue ?

**Comment by pingyang1117** [comment]
Thank you for bringing that to my attention. I have now updated it to the correct version.
