### ISSUE TITLE
Your license should include GPL

### ISSUE THREAD

**Issue by nikolay-gt** [pingyang1117/PRBNet_PyTorch#7]
You mention that "Many of the code is borrowed from YOLOv4, YOLOv5_obb, and YOLOv7". Your license currently is MIT, but e. g. YOLOv7 uses GPL-3 license, which is much more restrictive than MIT (see, e. g., answers here https://stackoverflow.com/questions/3902754/mit-vs-gpl-license )

**Comment by pingyang1117** [comment]
Thank you for bringing that to my attention. I have now updated it to the correct version.
